### ISSUE TITLE
When missformatting the roll by adding spaces, app errors

### ISSUE THREAD

**Issue by nagarutu** [obgr/eon-bot#9]
Running this in a docker container and when testing I found that when entering the roll incorrectly by adding a space (ie. '2d6 +2') the bot would outright crash.

I'm pretty novice at Python but have created a fork and will try to see if I can fix this, I figure a validation of the entry before running it will fix sort this.

Here's the error Im getting when it crashes:

```
/eon-bot

File app/main.py exists.

Starting app/main.py.

Logged in as EON-Bot#6811

Latency is 0.09995200112462044

Activity is playing: with cosmic demons

Debug is True

debug_guilds is None

Regex Debug

Regex NOT matched

cannot unpack non-iterable NoneType object

Bad Roll Debug

Ignoring exception in command ob:

Traceback (most recent call last):

  File "/eon-bot/app/modules/functions.py", line 135, in rollInfiniteDice

    number_of_rolls, sides_to_die, bonus = splitRollString(

TypeError: cannot unpack non-iterable NoneType object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/eon-bot/venv/lib/python3.10/site-packages/discord/commands/core.py", line 124, in wrapped

    ret = await coro(arg)

  File "/eon-bot/venv/lib/python3.10/site-packages/discord/commands/core.py", line 980, in _invoke

    await self.callback(ctx, **kwargs)

  File "/eon-bot/app/main.py", line 133, in ob

    results = rollInfiniteDice(ob_roll, debug)

  File "/eon-bot/app/modules/functions.py", line 163, in rollInfiniteDice

    print(sum_rolls)

UnboundLocalError: local variable 'sum_rolls' referenced before assignment

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/eon-bot/venv/lib/python3.10/site-packages/discord/bot.py", line 1114, in invoke_application_command

    await ctx.command.invoke(ctx)

  File "/eon-bot/venv/lib/python3.10/site-packages/discord/commands/core.py", line 375, in invoke

    await injected(ctx)

  File "/eon-bot/venv/lib/python3.10/site-packages/discord/commands/core.py", line 132, in wrapped

    raise ApplicationCommandInvokeError(exc) from exc

discord.errors.ApplicationCommandInvokeError: Application Command raised an exception: UnboundLocalError: local variable 'sum_rolls' referenced before assignment

```

**Comment by obgr** [comment]
Hi @nagarutu,
Thank you for your input.

At first glance it looks like the space in your roll input causes this and is not accepted by the regex.
It sure is something that could be fixed by parsing the input in a "forgiven syntax errors" function that allows spaces between the dice roll and the bonus.
This solution should not interfere with the queued rolls functionality (/qr) since the list expected is comma separated and not space separated.

I should also clean the code a bit any maybe enhance the logging/debug.
Br Olle

**Comment by nagarutu** [comment]
When playing around trying to trace the error, I realized It did not kill the process,
Should be good, but yepp better error messaging would be nice.

And maybe just adding handling to remove any invalid blank spaces.

**Comment by nagarutu** [comment]
Created PR  with basic approach to remove blank spaces in the rollInfiniteDice function

**Comment by nagarutu** [comment]
Also added the same fix to the rollForFight function as well.
